name: 'snowplow_utils'
version: '0.12.1'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: 'default'

macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "dbt_packages"
