name: 'snowplow_utils'
version: '0.6.0'
config-version: 2

require-dbt-version: [">=0.20.0", "<1.1.0"]

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "dbt_packages"
