name: Spark Deployment

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - 'feature/**'
      - 'dev'
      - 'staging'
      - 'template-spark-tests'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  deploy-spark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download JARs
      run: |
        chmod +x ./scripts/download_jars.sh
        ./scripts/download_jars.sh

    - name: Build and start Spark cluster
      run: |
        docker-compose -f docker/docker-compose.yml build
        docker-compose -f docker/docker-compose.yml up -d

    - name: Wait for services to start
      run: |
        echo "Waiting for Spark services to start..."
        sleep 60  # Increased wait time to ensure Thrift server is fully operational

    - name: Run network diagnostics
      run: |
        docker-compose -f docker/docker-compose.yml exec -T spark-master /bin/bash -c "/scripts/start-service.sh"
        docker-compose -f docker/docker-compose.yml exec -T spark-worker /bin/bash -c "/scripts/start-service.sh"
        docker-compose -f docker/docker-compose.yml exec -T thrift-server /bin/bash -c "/scripts/start-service.sh"

    - name: Run test Spark job
      run: |
        docker-compose -f docker/docker-compose.yml exec -T spark-master /spark/bin/spark-submit --class org.apache.spark.examples.SparkPi \
          --master spark://spark-master:7077 \
          --deploy-mode client \
          /spark/examples/jars/spark-examples*.jar 10

    - name: Verify Spark Thrift Server
      run: |
        docker-compose -f docker/docker-compose.yml exec -T thrift-server /spark/bin/beeline -u "jdbc:hive2://localhost:10000" -e "SHOW DATABASES; SHOW TABLES IN default;"

    - name: Cleanup
      if: always()
      run: docker-compose -f docker/docker-compose.yml down